### ISSUE TITLE
请教脱出来的dex用jadx反编译的时候出现大量的jadx.core.utils.exceptions.DecodeException: Load method exception: bogus opcode: 0073 in method

### ISSUE THREAD

**Issue by vxzhong** [dstmath/frida-unpack#4]
jadx反编译脱出来的dex，出现大量的下面的错误，不知道你有没有遇到过？是怎么修复的？
WARN  - Ignore decode error: 'bogus opcode: 0073', replace with NOP instruction
ERROR - Method load error: com.qihoo.util.Configuration.<clinit>():void
jadx.core.utils.exceptions.DecodeException: Load method exception: bogus opcode: 0073 in method: com.qihoo.util.Configuration.<clinit>():void, dex:
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:116)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:249)
	at jadx.core.ProcessClass.process(ProcessClass.java:31)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

谢谢

**Comment by yys-nixiang** [comment]
解决了吗，老哥
